apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gvf2whnby-python-gitops
  description: This is GitOps manifest for gvf2whnby-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gvf2whnby-python
    backstage.io/kubernetes-id: gvf2whnby-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gvf2whnby-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gvf2whnby-python
