apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gvf2whnby-python
  janus-idp.io/tekton: gvf2whnby-python
  backstage.io/kubernetes-id: gvf2whnby-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gvf2whnby-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
